### ISSUE TITLE
Human readable IAQ value range description

### ISSUE THREAD

**Issue by sergey-lukin** [thstielow/raspi-bme680-iaq#1]
Hello Thstielow!

We use esp32 with the Bosch bme680 sensors in our project. Thank you very much for sharing your Python script, providing a nice way to calculate IAQ value. It works just fine. No issues with that. Now, my boss is asking me if I can make him a chart like:
90-100% good air quality
70-80% ventilation is needed
60-70% move out
Under 60% poison
Or something similar
He explained that we need to provide a manual for people using our devices. The manual should contain some description of the IAQ value displayed on the screen of our devices.

I realize that there might be an issue with this kind of chart because the value is not absolute but relative to what was measured before. Maybe you have already thought about that before and have some idea. I will be thankful if you share your opinion about that.

Sergei Lukin

**Comment by thstielow** [comment]
Hello Sergei,

unfortunately, I can not give you such a table immediately.
I have been running the sensor mostly in an office environment and finding the exact value where ventilation is needed is quite tricky. However, defining such a table should be possible, as long as the sensor is allowed to burn-in in fresh air and is not running continiously in a dirty environment.
Typically, values down to 95% represent good air quality and I would estimate, that you can set the cut-off at 90%. Below, ventilation is recommended.
Currently, I do not have measurements for polluted environments but I may get the opportunity to record some values inside an engine research facility next week.
If you have the time I could try and provide an estimate for different degrees of pollution. Otherwise I would recommend you to do some trials in controlled environments to tailor the boundaries to your specific field of application.

Best,
Thomas

**Comment by sergey-lukin** [comment]
Hi Thomas!

Thank you very much for your prompt reply and for expressing your opinion. It sounds reasonable to me. And yes, we have some time still. We would be really thankful to you if you could find a possibility to record some values inside an engine research facility next week and share your results.

BR,
Sergei Lukin

**Comment by thstielow** [comment]
Hi Sergei,
unfortunately, my data collection did not yield the desired results.
However, it made me reconsider the humidity compensation, which I changed to work with the absolute himidity. 
I also reverted the logarithmic scaling of the AQ.
It now behaves much more similar to BSEC and re-scaling the AQ to a range of 0-500 should allow a comparison with the official chart.
Best,
Thomas
